# Generated by Django 5.0.2 on 2026-02-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom_timeslot_smarttimetable'),
        ('students', '0002_student_course_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
    ]
