# Generated by Django 5.0.2 on 2026-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_department_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
