# Generated by Django 5.0.2 on 2026-02-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentStaff',
        ),
    ]
