# Generated by Django 5.0.2 on 2026-03-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_roles', '0003_labschedule_nsseventparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nsseventparticipation',
            name='students',
        ),
        migrations.AddField(
            model_name='nsseventparticipation',
            name='department',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsseventparticipation',
            name='student_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsseventparticipation',
            name='year',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nsseventparticipation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DisciplineCase',
        ),
        migrations.DeleteModel(
            name='LabSchedule',
        ),
    ]
