# Generated by Django 5.0.2 on 2026-03-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_roles', '0004_remove_labschedule_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsseventparticipation',
            name='event',
        ),
    ]
