# Generated by Django 5.0.2 on 2026-02-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assetissue',
            name='status',
        ),
    ]
