# Generated by Django 5.0.2 on 2026-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_status_remove_assetissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('repair', 'Under Repair'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='working', max_length=20),
        ),
        migrations.AddField(
            model_name='assetissue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('repair', 'Under Repair'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
