# Generated by Django 5.0.2 on 2026-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_status_assetissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='scope',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LAB', 'Lab Equipment')], default='GENERAL', max_length=20),
        ),
    ]
