from django.shortcuts import render
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from students.models import Student
from attendance.models import Attendance 
from camp_fees.models import Fee   
from marks.models import Marks
from openpyxl import Workbook
from django.utils import timezone
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from attendance.models import AttendanceRecord
from openpyxl.styles import Font
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test

def is_admin(user):
    return user.is_superuser

def is_staff(user):
    return hasattr(user, 'staff')

def is_student(user):
    return hasattr(user, 'student')


def dashboard(request):
    return render(request, 'reports/dashboard.html')

@login_required
@user_passes_test(is_admin)
def student_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="students_report.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    normal_style = styles["Normal"]

    # ===== TITLE =====
    elements.append(Paragraph("CampSpark Student Report", styles['Title']))
    elements.append(Spacer(1, 20))

    students = Student.objects.all()

    # ===== TABLE HEADER =====
    data = [[
        "Roll No", "Name", "Department",
        "Year", "Phone", "Email"
    ]]

    for s in students:
        # WRAP TEXT SAFE
        name_para = Paragraph(s.name, normal_style)
        dept_para = Paragraph(s.department, normal_style)

        email = s.user.email if s.user else "N/A"

        row = [
            s.roll_number,
            name_para,
            dept_para,
            s.year,
            s.phone if s.phone else "N/A",
            email
        ]
        data.append(row)

    # ===== TABLE WIDTH CONTROL =====
    table = Table(
        data,
        repeatRows=1,
        colWidths=[70, 110, 120, 40, 90, 120]
    )

    # ===== TABLE STYLE =====
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),

        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # ===== FOOTER =====
    elements.append(Paragraph("Generated by CampSpark ERP", normal_style))
    elements.append(Paragraph("Authorized Signature", normal_style))

    doc.build(elements)
    return response

def attendance_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="attendance_report.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    normal_style = styles["Normal"]

    # ===== TITLE =====
    elements.append(Paragraph("CampSpark Attendance Report", styles['Title']))
    elements.append(Spacer(1, 20))

    # CORRECT MODEL
    records = AttendanceRecord.objects.select_related('student', 'attendance')

    # ===== TABLE HEADER =====
    data = [[
        "Roll No", "Name", "Department",
        "Date", "Status"
    ]]

    for r in records:
        s = r.student

        name_para = Paragraph(s.name, normal_style)
        dept_para = Paragraph(s.department, normal_style)

        status = "Present" if r.present else "Absent"
        date_text = r.attendance.date.strftime("%d-%m-%Y")

        row = [
            s.roll_number,
            name_para,
            dept_para,
            date_text,
            status
        ]
        data.append(row)

    # ===== TABLE WIDTH CONTROL =====
    table = Table(
        data,
        repeatRows=1,
        colWidths=[70, 120, 140, 80, 70]
    )

    # ===== TABLE STYLE =====
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),

        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # ===== FOOTER =====
    elements.append(Paragraph("Generated by CampSpark ERP", normal_style))
    elements.append(Paragraph("Authorized Signature", normal_style))

    doc.build(elements)
    return response

@login_required
@user_passes_test(is_admin)
def fees_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="fees_report.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    normal_style = styles["Normal"]

    # ===== TITLE =====
    elements.append(Paragraph("CampSpark Fees Report", styles['Title']))
    elements.append(Spacer(1, 20))

    fees = Fee.objects.select_related('student')

    # ===== TABLE HEADER =====
    data = [[
        "Roll No", "Name", "Department",
        "Total Fee", "Paid", "Due", "Status"
    ]]

    for f in fees:
        s = f.student

        name_para = Paragraph(s.name, normal_style)
        dept_para = Paragraph(s.department, normal_style)

        row = [
            s.roll_number,
            name_para,
            dept_para,
            f.total_amount,
            f.paid_amount,
            f.due_amount,
            f.status
        ]
        data.append(row)

    # ===== TABLE WIDTH CONTROL =====
    table = Table(
        data,
        repeatRows=1,
        colWidths=[70, 120, 130, 70, 60, 60, 70]
    )

    # ===== TABLE STYLE =====
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),

        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # ===== FOOTER =====
    elements.append(Paragraph("Generated by CampSpark ERP", normal_style))
    elements.append(Paragraph("Authorized Signature", normal_style))

    doc.build(elements)
    return response

@login_required
@user_passes_test(is_staff)
def marks_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="marks_table.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    normal_style = styles["Normal"]

    # ===== TITLE =====
    elements.append(Paragraph("CampSpark Official Mark Report", styles['Title']))
    elements.append(Spacer(1, 20))

    records = Marks.objects.select_related('student')

    # ===== STUDENT INFO BLOCK (TOP ONLY ONCE) =====
    first_record = records.first()
    if first_record:
        s = first_record.student
        sem_text = str(s.semester) if s.semester else "N/A"

        info_text = f"""
        <b>Student Name:</b> {s.name} <br/>
        <b>Department:</b> {s.department} <br/>
        <b>Semester:</b> {sem_text} <br/>
        <b>Year:</b> {s.year}
        """
        elements.append(Paragraph(info_text, normal_style))
        elements.append(Spacer(1, 15))

    # ===== TABLE HEADER (NO DEPT / YEAR REPEAT) =====
    data = [[
        "Roll No", "Name", "Subject",
        "Internal", "Semester", "Total", "Grade", "Result"
    ]]

    for m in records:
        student = m.student
        grade = m.grade()
        result = "PASS" if m.total >= 50 else "FAIL"

        # SUBJECT WRAP FIX
        subject_para = Paragraph(m.subject, normal_style)

        row = [
            student.roll_number,
            student.name,
            subject_para,
            m.internal_mark,
            m.semester_mark,
            m.total,
            grade,
            result
        ]
        data.append(row)

    # ===== TABLE WIDTH CONTROL =====
    table = Table(
        data,
        repeatRows=1,
        colWidths=[60, 90, 150, 50, 55, 45, 45, 55]
    )

    # ===== TABLE STYLE =====
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),

        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # ===== FOOTER =====
    elements.append(Paragraph("Generated by CampSpark ERP", normal_style))
    elements.append(Paragraph("Authorized Signature", normal_style))

    doc.build(elements)
    return response

@login_required
@user_passes_test(is_admin)
def excel_report(request):
    wb = Workbook()

    # ================= SUMMARY SHEET =================
    ws = wb.active
    ws.title = "Summary"

    bold = Font(bold=True)

    ws['A1'] = "CampSpark Analytics Report"
    ws['A1'].font = Font(bold=True, size=16)

    ws['A3'] = "Generated On:"
    ws['B3'] = str(timezone.now())

    ws['A5'] = "Total Students"
    ws['B5'] = Student.objects.count()

    ws['A6'] = "Total Marks Entries"
    ws['B6'] = Marks.objects.count()

    ws['A7'] = "Total Fees Records"
    ws['B7'] = Fee.objects.count()

    # ================= STUDENT SHEET =================
    ws2 = wb.create_sheet("Students")
    headers = ["Roll No", "Name", "Department", "Year", "Phone"]
    ws2.append(headers)

    for cell in ws2[1]:
        cell.font = bold

    for s in Student.objects.all():
        ws2.append([
            s.roll_number,
            s.name,
            s.department,
            s.year,
            s.phone or "N/A"
        ])

    # ================= MARKS SHEET =================
    ws3 = wb.create_sheet("Marks")
    headers = ["Roll No", "Name", "Subject", "Internal", "Semester", "Total"]
    ws3.append(headers)

    for cell in ws3[1]:
        cell.font = bold

    for m in Marks.objects.select_related('student'):
        ws3.append([
            m.student.roll_number,
            m.student.name,
            m.subject,
            m.internal_mark,
            m.semester_mark,
            m.total
        ])

    # ================= ATTENDANCE SHEET =================
    ws4 = wb.create_sheet("Attendance")
    headers = ["Roll No", "Name", "Date", "Status"]
    ws4.append(headers)

    for cell in ws4[1]:
        cell.font = bold

    for r in AttendanceRecord.objects.select_related('student', 'attendance'):
        status = "Present" if r.present else "Absent"
        ws4.append([
            r.student.roll_number,
            r.student.name,
            str(r.attendance.date),
            status
        ])

    # ================= FEES SHEET =================
    ws5 = wb.create_sheet("Fees")
    headers = ["Roll No", "Name", "Total", "Paid", "Due", "Status"]
    ws5.append(headers)

    for cell in ws5[1]:
        cell.font = bold

    for f in Fee.objects.select_related('student'):
        ws5.append([
            f.student.roll_number,
            f.student.name,
            f.total_amount,
            f.paid_amount,
            f.due_amount,
            f.status
        ])

    # ================= RESPONSE =================
    response = HttpResponse(
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename="CampSpark_Report.xlsx"'

    wb.save(response)
    return response

@login_required
@user_passes_test(is_student)
def semester_result_pdf(request, student_id):
    student = get_object_or_404(Student, id=student_id)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{student.name}_result.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    normal = styles["Normal"]

    elements.append(Paragraph("Semester Result Sheet", styles['Title']))
    elements.append(Spacer(1, 20))

    # STUDENT INFO
    info = f"""
    <b>Name:</b> {student.name}<br/>
    <b>Department:</b> {student.department}<br/>
    <b>Semester:</b> {student.semester}<br/>
    """
    elements.append(Paragraph(info, normal))
    elements.append(Spacer(1, 15))

    marks = Marks.objects.filter(student=student)

    data = [["Subject", "Internal", "Semester", "Total", "Grade", "Result"]]

    grand_total = 0

    for m in marks:
        grade = m.grade()
        result = "PASS" if m.total >= 50 else "FAIL"
        grand_total += m.total

        data.append([
            m.subject,
            m.internal_mark,
            m.semester_mark,
            m.total,
            grade,
            result
        ])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph(f"<b>Grand Total:</b> {grand_total}", normal))

    doc.build(elements)
    return response

@login_required
@user_passes_test(is_student)
def bonafide_pdf(request, student_id):
    student = get_object_or_404(Student, id=student_id)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="bonafide.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    elements.append(Paragraph("BONAFIDE CERTIFICATE", styles['Title']))
    elements.append(Spacer(1, 40))

    text = f"""
    This is to certify that <b>{student.name}</b>,
    Roll No <b>{student.roll_number}</b>,
    is a bonafide student of
    <b>{student.department}</b> department,
    studying in Year <b>{student.year}</b>.
    """

    elements.append(Paragraph(text, styles['Normal']))
    elements.append(Spacer(1, 60))

    elements.append(Paragraph("Authorized Signature", styles['Normal']))

    doc.build(elements)
    return response

@login_required
@user_passes_test(is_student)
def fee_certificate_pdf(request, student_id):
    student = get_object_or_404(Student, id=student_id)

    fees = Fee.objects.filter(student=student)
    total_paid = sum(f.paid_amount for f in fees)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="fee_certificate.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    elements.append(Paragraph("FEE PAID CERTIFICATE", styles['Title']))
    elements.append(Spacer(1, 40))

    text = f"""
    This is to certify that <b>{student.name}</b>
    (Roll No: {student.roll_number})
    has paid a total fee amount of
    <b>₹{total_paid}</b> successfully.
    """

    elements.append(Paragraph(text, styles['Normal']))
    elements.append(Spacer(1, 60))
    elements.append(Paragraph("Authorized Signature", styles['Normal']))

    doc.build(elements)
    return response

@login_required
@user_passes_test(is_staff)
def attendance_full_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="attendance_full.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    elements.append(Paragraph("Full Attendance Report", styles['Title']))
    elements.append(Spacer(1, 20))

    records = AttendanceRecord.objects.select_related('student', 'attendance')

    data = [["Roll", "Name", "Date", "Status"]]

    for r in records:
        status = "Present" if r.present else "Absent"
        data.append([
            r.student.roll_number,
            r.student.name,
            str(r.attendance.date),
            status
        ])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ]))

    elements.append(table)
    doc.build(elements)
    return response

def fee_certificate_pdf(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    fees = Fee.objects.filter(student=student)
    total_paid = sum(f.paid_amount for f in fees)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="fee_certificate.pdf"'

    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    # ===== OUTER BORDER (HALF PAGE) =====
    box_x = 70
    box_y = height - 420   # TOP HALF
    box_w = width - 140
    box_h = 360

    p.rect(box_x, box_y, box_w, box_h)

    # ===== COLLEGE NAME =====
    p.setFont("Helvetica-Bold", 18)
    p.drawCentredString(width / 2, box_y + box_h - 40,
                        "GOVERNMENT ARTS AND SCIENCE COLLEGE")

    p.setFont("Helvetica", 11)
    p.drawCentredString(width / 2, box_y + box_h - 60,
                        "Affiliated to State University")

    # ===== TITLE =====
    p.setFont("Helvetica-Bold", 14)
    p.drawCentredString(width / 2, box_y + box_h - 100,
                        "FEE PAID CERTIFICATE")

    # ===== BODY TEXT =====
    p.setFont("Helvetica", 11)
    text = f"""
This is to certify that {student.name},
Roll No {student.roll_number},
Department {student.department},
has successfully paid the total fee amount of ₹{total_paid}.
"""

    y_text = box_y + box_h - 150
    for line in text.split("\n"):
        p.drawString(box_x + 40, y_text, line)
        y_text -= 20

    # ===== SIGNATURE LINES =====
    p.line(box_x + 40, box_y + 60, box_x + 160, box_y + 60)
    p.drawString(box_x + 50, box_y + 40, "HOD Signature")

    p.line(box_x + box_w - 160, box_y + 60, box_x + box_w - 40, box_y + 60)
    p.drawString(box_x + box_w - 150, box_y + 40, "Principal Signature")

    # ===== FOOTER =====
    p.setFont("Helvetica-Oblique", 9)
    p.drawCentredString(width / 2, box_y + 15, "Generated by CampSpark ERP")

    p.showPage()
    p.save()
    return response