# Generated by Django 5.0.2 on 2026-01-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fees', '0001_initial'),
        ('students', '0002_student_course_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='amount_paid',
            new_name='due_amount',
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='Cash', max_length=50)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='camp_fees.fee')),
            ],
        ),
    ]
