# Generated by Django 5.0.2 on 2026-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fees', '0002_rename_amount_paid_fee_due_amount_fee_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
