# Generated by Django 5.0.2 on 2026-01-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fees', '0004_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
