# Generated by Django 5.0.2 on 2026-01-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Commerce', 'Commerce')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
