# Generated by Django 5.0.2 on 2026-01-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_exam'),
        ('marks', '0002_alter_marks_internal_mark_alter_marks_semester_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.exam'),
        ),
    ]
