# Generated by Django 5.0.2 on 2026-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_marks_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='graded_by',
        ),
    ]
