# Generated by Django 5.0.2 on 2026-02-03 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom_timeslot_smarttimetable'),
        ('camp_staff', '0002_staff_phone_alter_staff_department_and_more'),
        ('marks', '0004_remove_marks_date_added_remove_marks_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.exam'),
        ),
        migrations.AddField(
            model_name='marks',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp_staff.staff'),
        ),
    ]
