# Generated by Django 5.0.2 on 2026-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
